# Generated by Django 5.0.14 on 2025-10-10 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('user_is_staff', models.BooleanField(default=False)),
                ('user_is_superuser', models.BooleanField(default=False)),
                ('user_groups', models.JSONField(blank=True, default=list)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('method', models.CharField(blank=True, max_length=8, null=True)),
                ('path', models.CharField(blank=True, max_length=512, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('app_label', models.CharField(blank=True, max_length=64, null=True)),
                ('model', models.CharField(blank=True, max_length=64, null=True)),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('object_version', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('access', 'Access'), ('other', 'Other')], default='other', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('company_nif', models.CharField(blank=True, max_length=16, null=True)),
                ('fields_whitelist', models.JSONField(blank=True, default=list)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('payload_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['occurred_at'], name='auditlog_au_occurre_0253dd_idx'), models.Index(fields=['user_id'], name='auditlog_au_user_id_4c98bc_idx'), models.Index(fields=['company_nif'], name='auditlog_au_company_46cc70_idx'), models.Index(fields=['app_label', 'model', 'object_id'], name='auditlog_au_app_lab_28b38d_idx'), models.Index(fields=['action'], name='auditlog_au_action_92e229_idx')],
            },
        ),
    ]
