# Generated by Django 5.0.14 on 2025-10-30 18:13

import banking.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_tag', models.CharField(db_index=True, help_text='YYYY-MM', max_length=7)),
                ('pdf', models.FileField(upload_to=banking.models.statement_pdf_path)),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking.bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=512)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='banking.statement')),
            ],
        ),
        migrations.DeleteModel(
            name='BankJob',
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['bank', 'period_tag', 'user'], name='banking_sta_bank_id_0ceba0_idx'),
        ),
        migrations.AddIndex(
            model_name='statementline',
            index=models.Index(fields=['statement'], name='banking_sta_stateme_61df10_idx'),
        ),
    ]
